/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View } from 'react-native';
import ReactNativeMicrophone from 'react-native-microphone';

export default class App extends Component<{}> {
  state = {
    status: 'starting',
    message: '--'
  };
  componentDidMount() {
    ReactNativeMicrophone.init({
        bufferSize: 4096,
        sampleRate: 16000,
        bitsPerChannel: 16,
        channelsPerFrame: 1,
    });

    ReactNativeMicrophone.addListener(() => {
        console.log('gdgfd');
    })

    setTimeout(() => {
        ReactNativeMicrophone.start();
        this.setState({...this.state, status: 'recording...'})
    }, 2000);

    setTimeout(() => {
        ReactNativeMicrophone.stop();
        this.setState({...this.state, status: 'stoped!'})
    }, 5000);
  }
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆ReactNativeMicrophone example☆</Text>
        <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
        <Text style={styles.welcome}>☆NATIVE CALLBACK MESSAGE☆</Text>
        <Text style={styles.instructions}>{this.state.message}</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#AEFB56',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
